inherit: 
    - models/large.yaml
    - wandb.yaml

model:
    n_dims: 20 #10 (AR) #20 (ICL)
    n_positions: 101 #21 (AR) #101 (ICL)

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 300001 # 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
    device: cuda:0
